[package]
name = "oh-no"
version = "0.1.0"
edition = "2021"

[dependencies]
rocksdb = {version = "0.22.0",default-features = false, features = [] }
serde = "1.0.192"
serde_derive = "1.0.192"
serde_json = "1.0.108"

[dev-dependencies]
rand = "0.8.5"
