name: check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: oh-no
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: nix flake check
        run: nix flake check
